#!/usr/bin/env python3
"""Generate src/cpp/drivers/font8x16.cpp -- the 8x16 bitmap font used by the
framebuffer console (drivers/fb_console.cpp).

The glyphs are rasterized from DejaVu Sans Mono (Bitstream Vera derived,
permissive license) at a size that fits an 8x16 cell, then thresholded to one
bit per pixel. The generated file is checked in, so the build never needs
python or the font installed; re-run this only to regenerate it:

    python3 scripts/gen-font8x16.py > src/cpp/drivers/font8x16.cpp
"""

import sys
from PIL import Image, ImageDraw, ImageFont

FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
SIZE, XOFF, YOFF, THRESHOLD = 14, 0, 1, 110
FIRST, LAST = 0x20, 0x7E


def glyph(font, ch):
    img = Image.new("L", (8, 16), 0)
    ImageDraw.Draw(img).text((XOFF, YOFF), ch, font=font, fill=255)
    px = img.load()
    return [sum((1 << (7 - x)) for x in range(8) if px[x, y] > THRESHOLD)
            for y in range(16)]


def main():
    font = ImageFont.truetype(FONT, SIZE)
    out = sys.stdout
    out.write("/* Generated by scripts/gen-font8x16.py -- do not edit.\n"
              "   Glyphs rasterized from DejaVu Sans Mono (Bitstream Vera\n"
              "   derived, permissive license) into 8x16 monochrome cells. */\n\n"
              '#include "font8x16.h"\n\n'
              "namespace Kernel\n{\n\n"
              "const u8 Font8x16[Font8x16GlyphCount][Font8x16Height] = {\n")
    for code in range(FIRST, LAST + 1):
        rows = glyph(font, chr(code))
        name = chr(code) if code != 0x27 and code != 0x5C else "\\" + chr(code)
        out.write("    /* 0x%02x '%s' */ { %s },\n"
                  % (code, name, ", ".join("0x%02x" % r for r in rows)))
    out.write("};\n\n}\n")


main()
