#!/usr/bin/env python3
"""Generate src/cpp/drivers/font8x16.cpp -- the 8x16 bitmap font used by the
framebuffer console (drivers/fb_console.cpp).

The glyphs are rasterized from DejaVu Sans Mono (Bitstream Vera derived,
permissive license) and thresholded to one bit per pixel. Every glyph is
first drawn into a tall scratch cell; the 16 rows actually emitted are the
window that covers the ink of the whole character set, so nothing is
silently clipped -- getting that wrong costs you the underscore and every
descender. The script fails if a printable glyph would come out empty or
cropped.

The generated file is checked in, so the build needs neither python nor the
font. Re-run only to regenerate it:

    python3 scripts/gen-font8x16.py > src/cpp/drivers/font8x16.cpp
"""

import sys
from PIL import Image, ImageDraw, ImageFont

FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
SIZE, XOFF, THRESHOLD = 14, 0, 110
WIDTH, HEIGHT = 8, 16
SCRATCH_H, SCRATCH_TOP = 40, 12    # room above and below the cell
FIRST, LAST = 0x20, 0x7E


def raster(font, ch):
    """Render one glyph into the scratch cell as a list of bitmap rows."""
    img = Image.new("L", (WIDTH, SCRATCH_H), 0)
    ImageDraw.Draw(img).text((XOFF, SCRATCH_TOP), ch, font=font, fill=255)
    px = img.load()
    return [sum((1 << (WIDTH - 1 - x)) for x in range(WIDTH)
                if px[x, y] > THRESHOLD)
            for y in range(SCRATCH_H)]


def main():
    font = ImageFont.truetype(FONT, SIZE)
    tall = {code: raster(font, chr(code)) for code in range(FIRST, LAST + 1)}

    inked = [y for rows in tall.values() for y in range(SCRATCH_H) if rows[y]]
    top, bottom = min(inked), max(inked)
    if bottom - top + 1 > HEIGHT:
        sys.exit("ink spans %d rows, does not fit %d: lower SIZE"
                 % (bottom - top + 1, HEIGHT))

    # Centre the ink in the cell, biased up so the cursor underline on the
    # bottom row does not collide with descenders.
    origin = max(0, top - (HEIGHT - (bottom - top + 1)) // 2)

    for code, rows in tall.items():
        if code == 0x20:
            continue
        if not any(rows):
            sys.exit("glyph 0x%02x rendered empty" % code)
        kept = rows[origin:origin + HEIGHT]
        if sum(bin(r).count("1") for r in kept) != \
           sum(bin(r).count("1") for r in rows):
            sys.exit("glyph 0x%02x is cropped by the cell window" % code)

    out = sys.stdout
    out.write("/* Generated by scripts/gen-font8x16.py -- do not edit.\n"
              "   Glyphs rasterized from DejaVu Sans Mono (Bitstream Vera\n"
              "   derived, permissive license) into 8x16 monochrome cells. */\n\n"
              '#include "font8x16.h"\n\n'
              "namespace Kernel\n{\n\n"
              "const u8 Font8x16[Font8x16GlyphCount][Font8x16Height] = {\n")
    for code in range(FIRST, LAST + 1):
        rows = tall[code][origin:origin + HEIGHT]
        name = chr(code) if code not in (0x27, 0x5C) else "\\" + chr(code)
        out.write("    /* 0x%02x '%s' */ { %s },\n"
                  % (code, name, ", ".join("0x%02x" % r for r in rows)))
    out.write("};\n\n}\n")


main()
